spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

public-data-portal:
  key:
    encode: ${PUBLIC_DATA_PORTAL_ENDCODE_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-time: 3600000 # 1 Hour
  refresh-token-expire-time: 1209600000 # 2 Weeks

bustracker:
  nats:
    url: ${NATS_URL}
    connection-name: ${NATS_CONNECTION_NAME}
    request-timeout-ms: 2000
  cache:
    station-search:
      ttl-minutes: 30
  sse:
    interval-seconds: 15